### PR TITLE
Rename Deployer health checks into readiness checks

### PR DESCRIPTION
**Pull request by MrBatschner**
**How to categorize this PR?**

/area deployers
/kind technical-debt
/kind api-change
/priority 4

**What this PR does / why we need it**:

Following up with a comment by @schrodit in PR #225 this PR renames the health check of the deployers into readiness checks to be in line with the Kubernetes naming convention and to pave the ground for potential future liveness checks.

**Which issue(s) this PR fixes**:
n.a.

**Special notes for your reviewer**:

PR #225 must be approved and merged first before this one can be merged as it builds on top of the changes introduced by that PR. 
PR will remain in Draft status until #225 gets merged.

**Release note**:

```other operator
Deployer healthchecks renamed into readiness checks.
```

### CODE REVIEW

**Review by schrodit — APPROVED** [review]
/lgtm

**Comment by MrBatschner** [comment]
PR #225 got merged so...
/ready-for-review

**Pull request merged**
