### PR TITLE
Remove dependency breaking build under Mac

### PR DESCRIPTION
**Pull request by Nikolay-Neykov**
**How to categorize this PR?**
/area os
/kind bug
/priority normal

**What this PR does / why we need it**:
The folders **./vendor/github.com/googleapis/gnostic/OpenAPIv2** and **./vendor/github.com/googleapis/gnostic/openapiv2** are considered the same folders under Mac. Which results to **openapiv2** folder not cloned by git when cloning the repository. This is resulting to landscaper build not able to run on Mac because the dependency is not available.

**Special notes for your reviewer**:
Not sure if OpenAPIv2 folder is used on its own on other OS.

**Steps to reproduce**
1. Clone the repository under Mac.
2. The following warning can be seen:
```warning: the following paths have collided (e.g. case-sensitive paths on a case-insensitive filesystem) and only one from the same```
2. Under **./vendor/github.com/googleapis/gnostic/** folder only **OpenAPIv2** folder is available and **openapiv2** is missing.
3. Run ```make docker-images``` which results to error with not satisfied dependency:
```
=> [builder 3/4] COPY . .                                                                                                                     1.5s
 => ERROR [builder 4/4] RUN make install EFFECTIVE_VERSION=$EFFECTIVE_VERSION                                                                  1.8s
------                                                                                                                                              
 > [builder 4/4] RUN make install EFFECTIVE_VERSION=$EFFECTIVE_VERSION:                                                                             
#11 1.674 vendor/k8s.io/client-go/discovery/discovery_client.go:30:2: cannot find package "." in:                                                   
#11 1.674 	/go/src/github.com/gardener/landscaper/vendor/github.com/googleapis/gnostic/openapiv2
#11 1.679 make: *** [Makefile:54: install] Error 1
------
executor failed running [/bin/sh -c make install EFFECTIVE_VERSION=$EFFECTIVE_VERSION]: exit code: 2
make: *** [docker-images] Error 1
```

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @Nikolay-Neykov for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by schrodit — CHANGES_REQUESTED** [review]
Oh yes I also had some issues with that renaming.
But I think the `vendor/github.com/googleapis/gnostic/openapiv2` package is required.
So can you only delete the `vendor/github.com/googleapis/gnostic/OpenAPIv2`?

**Comment by Nikolay-Neykov** [comment]
Yep, it was a mistake. I think it should be ok now.

**Comment by schrodit** [comment]
thanks
/ok-to-test

**Review by schrodit — APPROVED** [review]
/lgtm

**Pull request merged**
