### PR TITLE
Component Descriptor Imports

### LINKED ISSUE #222: Add component descriptor as blueprint import
**How to categorize this issue?**

/area delivery
/kind enhancement
/priority 2

**What would you like to be added**:

Currently it is possible to import dataobjects or targets (targetlists).
But as some component require additional information from component descriptor that are not part of their own component descriptor it is necessary to have them as import.

So it should be possible for blueprints to define imports of type ComponentDescriptor or a list of component descriptors.
In the installation these imports can then be satisfied by either providing the import directly or referecing it using a componentName and version
```
imports:
  componentDescriptors:
  - name: my-import
    configMap: ...
  - name: my-other-cd
    componentName: abc
    version: 123
```

### PR DESCRIPTION
**Pull request by Diaphteiros**
**How to categorize this PR?**

/area usability
/kind enhancement
/priority 2

**Which issue(s) this PR fixes**:
Fixes #222

**Special notes for your reviewer**:

**Release note**:

```feature user
It is now possible to import component descriptors. See the documentation for [blueprints](docs/usage/Blueprints.md#component-descriptors) and [installations](docs/usage/Installations.md#component-descriptor-imports) for more information.
```

### CODE REVIEW

**Review by schrodit — CHANGES_REQUESTED** [review]
first round of review

**Review by robertgraeff — COMMENTED** [review]
Hi, 
suppose I want to use a resource from an imported component descriptor as blueprint in a subinstallation, Is there a special syntax for this?

**Comment by Diaphteiros** [comment]
I don't think that this is possible at the moment.

**Comment by schrodit** [comment]
> Hi,
> suppose I want to use a resource from an imported component descriptor as blueprint in a subinstallation, Is there a special syntax for this?

can you think of a use case for that feature?

**Comment by robertgraeff** [comment]
> can you think of a use case for that feature?

No particular use case. I just found the syntax below for a blueprint coming from a referenced component and wondered whether the blueprint could also come from an imported component. That's all.
```yaml
  blueprint:
    ref: cd://componentReferences/ingress/resources/blueprint 
```

**Review by robertgraeff — APPROVED** [review]

**Review by schrodit — APPROVED** [review]
/lgtm

**Pull request merged**
