### PR TITLE
Update Installations.md

### PR DESCRIPTION
**Pull request by morri-son**
correct typo

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @morri-son for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by morri-son** [comment]
reviewed/ok-to-test

**Comment by morri-son** [comment]
/reviewed/ok-to-test

**Review by guewa — APPROVED** [review]

**Pull request merged**
