### PR TITLE
usage of correct repository context

### PR DESCRIPTION
**Pull request by reshnm**
**How to categorize this PR?**

/area usability
/kind bug
/priority 3

**What this PR does / why we need it**:

Currently the correct repository context (set via installation, Landscaper Context or Component Overwrite) is not used while resolving component descriptors and resources.
This PR enables the usage of the correct repository context in various places and adds test to find regressions.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by achimweigel — CHANGES_REQUESTED** [review]
The coding looks good to me.

I think the possibility to specify a repository context at so many different location is very confusing for the end user (and for me :-) ):

- [Default repo context in landscaper](https://github.com/gardener/landscaper/blob/4f17eb467cc6cb400fe1effa22c4fb1db64d677d/apis/config/v1alpha1/types_landscaper_config.go#L24) 
- [Installation alternative 1](https://github.com/gardener/landscaper/blob/4f17eb467cc6cb400fe1effa22c4fb1db64d677d/apis/core/types_installation.go#L49)
- [Installation alternative 2](https://github.com/gardener/landscaper/blob/4f17eb467cc6cb400fe1effa22c4fb1db64d677d/apis/core/types_installation.go#L45)

I'm not sure if there are other possibilities. Currently this information is somehow spread in the documentation (e.g. [link1](https://github.com/gardener/landscaper/blob/master/docs/usage/Context.md), [link2](https://github.com/gardener/landscaper/blob/master/docs/usage/Installations.md)). Might it be possible and a good idea to combine and relate the different possibilities?

**Comment by reshnm** [comment]
> The coding looks good to me.
> 
> I think the possibility to specify a repository context at so many different location is very confusing for the end user (and for me :-) ):
> 
>     * [Default repo context in landscaper](https://github.com/gardener/landscaper/blob/4f17eb467cc6cb400fe1effa22c4fb1db64d677d/apis/config/v1alpha1/types_landscaper_config.go#L24)
> 
>     * [Installation alternative 1](https://github.com/gardener/landscaper/blob/4f17eb467cc6cb400fe1effa22c4fb1db64d677d/apis/core/types_installation.go#L49)
> 
>     * [Installation alternative 2](https://github.com/gardener/landscaper/blob/4f17eb467cc6cb400fe1effa22c4fb1db64d677d/apis/core/types_installation.go#L45)
> 
> 
> I'm not sure if there are other possibilities. Currently this information is somehow spread in the documentation (e.g. [link1](https://github.com/gardener/landscaper/blob/master/docs/usage/Context.md), [link2](https://github.com/gardener/landscaper/blob/master/docs/usage/Installations.md)). Might it be possible and a good idea to combine and relate the different possibilities?

I agree with you. There is actually another possibility with component overwrites, which is currently being worked on:
https://github.com/gardener/landscaper/pull/430

We should definately document this better. However, I would like to wait until the changes with the component overwrite are done and the document the complete picture. What do you think?

**Comment by achimweigel** [comment]
That's a good idea.

**Review by achimweigel — APPROVED** [review]
/lgtm

**Pull request merged**
